fullnameOverride: api
deployment:
  replicas: 0
  image:
    pullPolicy: IfNotPresent
    repository: agnjunio/albion-killbot
    tag: 4.23.9
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  command:
  - /bin/bash
  - -c
  - npm run start:api
  env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          name: discord-secrets
          key: DISCORD_TOKEN
    - name: DISCORD_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: discord-secrets
          key: DISCORD_CLIENT_ID
    - name: DISCORD_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: discord-secrets
          key: DISCORD_CLIENT_SECRET
    - name: DASHBOARD_URL
      value: https://albion-killbot-dashboard.k8scicd.local
    - name: AMQP_URL
      value: amqp://rabbitmq
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongodb-secrets
          key: MONGODB_URL
    - name: DEBUG_LEVEL
      value: debug
service:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: http
