apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

resources:
- virtual-service.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/community-charts/n8n
- name: n8n
  repo: https://community-charts.github.io/helm-charts
  version: 1.16.29
  valuesFile: values.yaml
  releaseName: n8n
  includeCRDs: true