apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: n8n-virtualservice
spec:
  gateways:
    - istio-ingress/global-gateway
  hosts:
    - n8n.k8scicd.local
  http:
    - route:
      - destination:
          host: n8n
          port:
            number: 5678