---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: etcd
  publishNotReadyAddresses: true
  ports:
  - name: etcd-client
    port: 2379
  - name: etcd-server
    port: 2380
  - name: etcd-metrics
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-lb
  labels:
    app: etcd
spec:
  type: LoadBalancer
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
      name: client
  selector:
    app: etcd