apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../../../../base/argocd
- application.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 7.8.24
  valuesFile: ../../../../../base/argocd/values.yaml
  releaseName: argocd
  includeCRDs: true
  valuesMerge: merge
  valuesInline:
    configs:
      cm:
        url: https://argocd.k8scicd.local
        dex.config: |
          connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Ov23liLcbPQqSK4quiX4
              clientSecret: $dex-github-secret:dex.github.clientSecret
      rbac:
        create: true
        policy: |
          g, ymedlop@gmail.com, role:admin
        policy.default: role:readonly
        scopes: '[groups, email]'