fullnameOverride: crawler
deployment:
  replicas: 0
  image:
    pullPolicy: IfNotPresent
    repository: agnjunio/albion-killbot
    tag: 4.23.9
  command:
  - /bin/bash
  - -c
  - npm run start:crawler
  env:
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongodb-secrets
          key: MONGODB_URL
    - name: AMQP_URL
      value: amqp://rabbitmq