apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: albion-killbot

resources:
- api
- bot
- crawler
- dashboard
- nginx
- rabbitmq

helmGlobals:
 chartHome: ../../../../../charts