apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-gtw-tls
  namespace: kube-system
spec:
  secretName: argocd-gtw-tls
  issuerRef:
    name: selfsigned
    kind: Issuer
  subject:
    organizations:
    - cluster.local
    - cert-manager
  commonName: "*.homelab.local"
  dnsNames:
  - "*.homelab.local"
