apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-gtw-tls
  namespace: kube-system
spec:
  secretName: traefik-gtw-tls
  dnsNames:
  - *.homelab.local
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
