micro-nodejs:
  fullnameOverride: bot
  deployment:
    replicas: 0
    image:
      pullPolicy: IfNotPresent
      repository: agnjunio/albion-killbot
      tag: 4.23.9
    command:
    - /bin/bash
    - -c
    - npm run start:bot
    env:
      - name: DISCORD_TOKEN
        valueFrom:
          secretKeyRef:
            name: discord-secrets
            key: DISCORD_TOKEN
      - name: MONGODB_URL
        valueFrom:
          secretKeyRef:
            name: mongodb-secrets
            key: MONGODB_URL
      - name: AMQP_URL
        value: amqp://rabbitmq