apiVersion: v1
kind: ServiceAccount
metadata:
  name: k3s-pi
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-pi-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: k3s-pi
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: k3s-pi-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: k3s-pi
type: kubernetes.io/service-account-token