apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://istio.io/latest/docs/setup/install/helm/
# https://artifacthub.io/packages/helm/istio-official/base
- name: base
  namespace: istio-system
  includeCRDs: true
  repo: https://istio-release.storage.googleapis.com/charts/
  version: 1.25.1
  # valuesFile: ../../../../../base/istio-system/values.yaml
  releaseName: base
# https://artifacthub.io/packages/helm/istio-official/istiod
- name: istiod
  namespace: istio-system
  repo: https://istio-release.storage.googleapis.com/charts/
  version: 1.25.1
  valuesFile: ../../../../../base/istio-system/values.yaml
  releaseName: istiod