apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dashboard-virtualservice
spec:
  gateways:
    - istio-ingress/global-gateway
  hosts:
    - albion-killbot-dashboard.k8scicd.local
  http:
    - route:
      - destination:
          host: nginx
          port:
            number: 80