apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
# https://artifacthub.io/packages/helm/grafana/loki∫
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 7.0.0
    releaseName: loki
    namespace: logging
    valuesFile: values.yaml
# https://artifacthub.io/packages/helm/grafana/promtail
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.1
    releaseName: promtail
    namespace: logging
    valuesFile: promtail-values.yaml