deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  limits_config:
    retention_period: 30d
  compactor:
    retention_enabled: true
    retention_delete_delay: 2h

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: ugreen-nfs
    accessModes:
      - ReadWriteOnce
    size: 20Gi

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false

resultsCache:
  enabled: false

gateway:
  enabled: false

test:
  enabled: false