deploymentMode: SingleBinary

loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2026-06-14"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  limits_config:
    retention_period: 30d
  compactor:
    retention_enabled: true
    retention_delete_delay: 2h

singleBinary:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: k3s-gengar
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: ugreen-nfs
    accessModes:
      - ReadWriteOnce
    size: 20Gi

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0