apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-definitions
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters: {}
      - git:
          repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
          revision: &branch main
          directories:
          - path: clusters/groups/on-prem/{{name}}/k8s-definitions/*
  template:
    metadata:
      name: '{{name}}-{{path[5]}}'
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: *branch
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{path[5]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
